require('dotenv').config();
const express=require('express');const play=require('play-dl');const {Client,GatewayIntentBits,REST,Routes,SlashCommandBuilder,EmbedBuilder}=require('discord.js');const {createAudioPlayer,createAudioResource,joinVoiceChannel,AudioPlayerStatus,getVoiceConnection}=require('@discordjs/voice');
const tokens=(process.env.BOT_TOKENS||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,10);if(!tokens.length)throw new Error('BOT_TOKENS is required');
const app=express();app.get('/',(_,r)=>r.json({ok:true,bots:tokens.length}));app.get('/health',(_,r)=>r.json({ok:true}));app.listen(process.env.PORT||3000,'0.0.0.0');
const cmds=['play','skip','stop','queue','nowplaying','leave','help'].map(n=>{const c=new SlashCommandBuilder().setName(n).setDescription(n==='play'?'تشغيل أغنية':'Music command');return n==='play'?c.addStringOption(o=>o.setName('query').setDescription('اسم الأغنية أو الرابط').setRequired(true)).toJSON():c.toJSON()});
const states=new Map();function state(client,gid){let s=states.get(client.user.id);if(!s)states.set(client.user.id,s={guilds:new Map()});if(!s.guilds.has(gid)){const player=createAudioPlayer();const x={player,queue:[],current:null,channel:null};player.on(AudioPlayerStatus.Idle,()=>next(client,gid));player.on('error',()=>next(client,gid));s.guilds.set(gid,x)}return s.guilds.get(gid)}
async function next(client,gid){const x=state(client,gid),t=x.queue.shift();if(!t){x.current=null;return}try{const s=await play.stream(t.url,{quality:2,discordPlayerCompatibility:true});x.current=t;x.player.play(createAudioResource(s.stream,{inputType:s.type}));if(x.channel)await x.channel.send({embeds:[new EmbedBuilder().setColor(0x7c3aed).setTitle('▶️ Playing Song').setDescription('['+t.title+']('+t.url+')')]}).catch(()=>{})}catch(e){next(client,gid)}}
async function track(q){if(/^https?:\/\//i.test(q))return{url:q,title:q};const r=await play.search(q,{limit:1,source:{youtube:'video'}});if(!r.length)throw Error('لم أجد الأغنية');return{url:r[0].url,title:r[0].title}}
async function run(c,i){if(!i.isChatInputCommand())return;const x=state(c,i.guildId);x.channel=i.channel;try{if(i.commandName==='help')return i.reply({content:'الأوامر: /play /skip /stop /queue /nowplaying /leave',ephemeral:true});if(i.commandName==='play'){await i.deferReply();const vc=i.member.voice.channel;if(!vc)throw Error('ادخل روم صوتي أولاً');x.connection=joinVoiceChannel({channelId:vc.id,guildId:vc.guild.id,adapterCreator:vc.guild.voiceAdapterCreator});x.connection.subscribe(x.player);const t=await track(i.options.getString('query'));x.queue.push(t);if(x.player.state.status!==AudioPlayerStatus.Playing&&x.player.state.status!==AudioPlayerStatus.Buffering)await next(c,i.guildId);return i.editReply('تمت الإضافة: **'+t.title+'**')}if(i.commandName==='skip'){x.player.stop();return i.reply('تم التخطي')}if(i.commandName==='stop'){x.queue=[];x.player.stop();return i.reply('تم الإيقاف')}if(i.commandName==='queue')return i.reply((x.current?'الحالية: '+x.current.title+'\n':'')+(x.queue.map((t,n)=>n+1+'. '+t.title).join('\n')||'القائمة فارغة'));if(i.commandName==='nowplaying')return i.reply(x.current?'🎶 '+x.current.title:'لا توجد أغنية');if(i.commandName==='leave'){x.queue=[];x.player.stop();getVoiceConnection(i.guildId)?.destroy();return i.reply('خرجت من الروم')}}catch(e){if(i.deferred)return i.editReply(e.message);return i.reply({content:e.message,ephemeral:true})}}
for(const token of tokens){const c=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildVoiceStates]});c.once('ready',async()=>{console.log(c.user.tag+' online');const rest=new REST({version:'10'}).setToken(c.token);const route=process.env.TEST_GUILD_ID?Routes.applicationGuildCommands(c.user.id,process.env.TEST_GUILD_ID):Routes.applicationCommands(c.user.id);await rest.put(route,{body:cmds})});c.on('interactionCreate',i=>run(c,i));c.login(token)}
